language: node_js
node_js:
  - "8"
notifications:
  email:
    recipients:
      - aircity@drrr.us
    on_success: change
    on_failure: always
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    branch: master
