language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "aircity@drrr.us"
        api_key: $NPM_API_KEY
        gem: vue-cli-plugin-pages
        on: deploy-npm-release
